# Site settings
title: Template
client:
  name: Client Name
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
# core-se-link: https://www.secretescapes.de/aktuelle-angebote # DE
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/template" # the subpath of the site, including territory and year
img:     "/uk/2020/template/_assets/img"
css:     "/uk/2020/template/_assets/css"
js:      "/uk/2020/template/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed